"""`GET/POST/DELETE /api/v1/allowlist` (ADDENDUM.md A2)."""

from datetime import UTC, datetime
from typing import Any

from fastapi import APIRouter, HTTPException

from pirewall.api.app import RpcClientDep, SessionDep
from pirewall.api.schemas import AllowlistCreateRequest, MessageResponse
from pirewall.core.models.allowlist import AllowlistEntry

router = APIRouter(prefix="/api/v1/allowlist", tags=["allowlist"])


@router.get("", response_model=list[AllowlistEntry])
def list_allowlist(rpc_client: RpcClientDep) -> list[AllowlistEntry]:
    return rpc_client.list_allowlist()


@router.post("")
def add_allowlist_entry(
    body: AllowlistCreateRequest, rpc_client: RpcClientDep, session: SessionDep
) -> dict[str, Any]:
    """Add an allowlist entry, optionally provisioning a portal account with it.

    Returns the entry as JSON, plus `portal_username`/`portal_password` when
    one was provisioned (ADDENDUM_3.md C3). The password is generated by
    pirewall-core, returned here exactly once, and never stored in readable
    form — so this response is the only chance to record it.

    Not declared with `response_model=AllowlistEntry`: that would strip the
    two portal fields off the response, silently discarding the only copy of
    a password an admin was told they would be shown.
    """
    entry = AllowlistEntry(
        target=body.target,
        port=body.port,
        protocol=body.protocol,
        reason=body.reason,
        created_at=datetime.now(UTC),
        created_by=session.username,
    )
    return rpc_client.add_allowlist_entry_with_portal_user(entry, body.portal_username)


@router.delete("/{entry_id}", response_model=MessageResponse)
def remove_allowlist_entry(entry_id: str, rpc_client: RpcClientDep) -> MessageResponse:
    removed = rpc_client.remove_allowlist_entry(entry_id)
    if not removed:
        raise HTTPException(status_code=404, detail="allowlist entry not found")
    return MessageResponse(message="removed")
